/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.interpreter.lox;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        Lox classUnderTest = new Lox();
    }
}
